version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    command: redis-server --bind 0.0.0.0
    ports:
      - "6380:6379"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shotr
    ports:
      - "5433:5432"
    networks:
      - app-network

  app:
    build: .
    container_name: shotr-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - app-network
    command: sh -c "npx prisma migrate deploy && node dist/server/index.js"

networks:
  app-network:
    driver: bridge
